---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: './test/environments'
  roles_path: './test/roles'

platforms:
  - name: ubuntu-12.04
    driver_config:
        box: opscode-ubuntu-12.04
        box_url: http://files.vagrantup.com/precise32.box

suites:
  - name: default
    run_list:
      - recipe[]
    attributes:
    provisioner:
        solo.rb:
            environment:
